mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('registration/', include('registration.urls', namespace='registration')),
    path('shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'
urlpatterns = [
    # path('shop/', views.Shop.as_view(), name='shop'),
    path('product_view/', views.ShowProductView.as_view(), name='product_view'),
    path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),

    path('add_to_wishlist/<int:pk>/', views.AddProductToWishlist.as_view(), name='add_to_wishlist'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('remove_item/<int:pk>/', views.RemoveFromWishlist.as_view(), name='remove_item'),

    path('add_to_cart/<int:pk>/', views.AddProductToCart.as_view(), name="add_to_cart"),
    # path('cart/', views.CartView.as_view(), name='cart'),
    path('remove_from_cart/<int:pk>/', views.RemoveFromCart.as_view(), name='remove_from_cart'),

    path('cart_update/<int:pk>/', views.CartFormSetUpdateView.as_view(), name='cart_update'),

    path('user_info/', views.UserInfoView.as_view(), name='user_info'),
    path('order/', views.OrderView.as_view(), name='order')

]

shop/models.py
from django.db import models

# Create your models here.

shop/forms.py
from django import forms
from myapp.models import Wishlist
from myapp.models import Cart, UserInfo, User


# ---------------------------->   FORMSET  CART  <--------------------------
class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['product_qty', 'total_price']

    def __init__(self, *args, **kwargs):  # user not able to edit
        super().__init__(*args, **kwargs)
        self.fields['total_price'].widget.attrs['readonly'] = True


class UserInfoForm(forms.ModelForm):
    # address = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))  for addition_field widgets--OR-->

    class Meta:
        model = UserInfo
        fields = ('address', 'pincode', 'city', 'state')

        widgets = {
            'address': forms.Textarea(attrs={'rows': 4, 'cols': 4}),
        }

shop/views.py
from django.shortcuts import redirect
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView

from shop.forms import CartForm, UserInfoForm
from myapp.models import Product, Wishlist, Cart, UserInfo
from django.contrib import messages
from django.forms import modelformset_factory
from django.urls import reverse


class ShowProductView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'shop.html'
    context_object_name = 'products'  # in html data display from this name


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'userdata'

    def get_context_data(self, **kwargs):  # if add then  remove button appear---> if in product_detail.html
        context = super().get_context_data(**kwargs)
        context['wishlist_obj'] = Wishlist.objects.filter(user=self.request.user.usercreate,
                                                          product=self.object).first()

        context['cart_obj'] = Cart.objects.filter(user=self.request.user.usercreate,
                                                  product=self.object).first()
        return context


class AddProductToWishlist(LoginRequiredMixin, View):

    def post(self, request, **kwargs):
        user = self.request.user.usercreate  # LOGIN USER
        product = Product.objects.get(id=self.kwargs.get('pk'))  # to fetch the id's data from Product model
        Wishlist.objects.create(user=user, product=product)  # to save the data
        messages.success(request, " Product has been added to the wishlist !! ")  # print through for loop in html
        return redirect('shop:product_detail', product.id)  # kwargs we use only in reverse!! to stay that same page
        # return redirect('shop:product_view')  # to go again in shop page


class WishlistView(LoginRequiredMixin, ListView):
    model = Wishlist
    template_name = 'wishlist/wishlist.html'

    def get_context_data(self, **kwargs):
        context = super(WishlistView, self).get_context_data(**kwargs)
        context["wishlist_count"] = len(self.model.objects.filter(user=self.request.user.usercreate))
        # take len of data in the name of wishlist_count print at the sidebar

        # context['cart_object'] = Cart.objects.filter(user=self.request.user.usercreate,
        #                                              product=self.object_list)
        return context


class RemoveFromWishlist(LoginRequiredMixin, View):

    def post(self, request, **kwargs):
        user = self.request.user.usercreate  # login user
        wishlist_item = Wishlist.objects.get(user=user, id=self.kwargs.get('pk'))
        wishlist_item.delete()
        messages.success(request, 'Product has been removed successfully')
        return redirect('shop:wishlist')


# when we click on cart-button from product_detail.html at that time it save product in the backend
# and now we ll make list view to show that data that is CartView
class AddProductToCart(LoginRequiredMixin, View):

    def post(self, request, **kwargs):
        user = self.request.user.usercreate
        product = Product.objects.get(id=self.kwargs.get('pk'))
        product_qty = 1
        total_price = product.product_price * product_qty
        Cart.objects.create(user=user, product=product, product_qty=product_qty, total_price=total_price)
        messages.success(request, " Product has been added to the Cart !! ")
        return redirect('shop:product_detail', product.id)


class RemoveFromCart(LoginRequiredMixin, View):
    def post(self, request, **kwargs):
        user = self.request.user.usercreate
        cart_item = Cart.objects.get(user=user, id=self.kwargs.get('pk'))
        cart_item.delete()
        messages.success(request, 'Product has been removed successfully')
        return redirect('shop:product_view')


#  ---------------------------->   FORMSET  CART  <--------------------------
# class CartFormSetView(View):
#     template_name = 'cart/cart.html'
#
#     def get(self, request):
#         CartFormSet = modelformset_factory(Cart, form=CartForm, extra=0)
#         formset = CartFormSet(queryset=Cart.objects.filter(user=request.user.usercreate))
#         return render(request, self.template_name, {'formset': formset})
#
# def post(self, request):
#     CartFormSet = modelformset_factory(Cart, form=CartForm, extra=1)
#     formset = CartFormSet(request.POST)
#     if formset.is_valid():
#         formset.save()
#         return redirect('shop:product_view')
#     return render(request, self.template_name, {'formset': formset})
# -----------------------above code converted ----------------------


class CartFormSetUpdateView(LoginRequiredMixin, UpdateView):
    model = Cart
    template_name = 'cart/cart.html'
    fields = []

    def get_success_url(self):
        return reverse('shop:user_info')
        # return reverse('shop:cart_update', kwargs={'pk': self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        CartFormSet = modelformset_factory(Cart, form=CartForm, extra=0)
        if self.request.POST:
            cart_formset = CartFormSet(self.request.POST,
                                       queryset=Cart.objects.filter(user=self.request.user.usercreate),
                                       prefix='cart_formset')  # when Id generate at that time start with prefix name

        else:
            cart_formset = CartFormSet(queryset=Cart.objects.filter(
                user=self.request.user.usercreate),
                prefix='cart_formset')  # queryset =user's data take from backend & show in table
        context['total_items'] = len(self.model.objects.filter(user=self.request.user.usercreate))  # count total item
        context['cart_formset'] = cart_formset

        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['cart_formset']
        if formset.is_valid():
            for form in formset:
                form.instance.user = self.request.user.usercreate
                form.save()
        return super().form_valid(form)


class UserInfoView(LoginRequiredMixin, CreateView):
    model = UserInfo
    form_class = UserInfoForm
    template_name = 'cart/userinfo.html'

    def get_success_url(self):
        return reverse('shop:order')

    def form_invalid(self, form):
        print(">>>>>>>>", form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        print(">>>>>>>>", form.errors)
        if form.is_valid():
            form.instance.user = self.request.user.usercreate
        return super().form_valid(form)


class OrderView(TemplateView):
    template_name = 'cart/order.html'

# messages.success("Your information has been submitted")

shop/templates/product_detail.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <main id="main" class="main">

        <div class="card mb-3">

            {% for message in messages %}
                <p style="font-weight: bold; text-align: center">{{ message }}</p>
            {% endfor %}

            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ userdata.product_image.url }}" class="img-fluid rounded-start mt-4 mb-4" alt="..."
                         style="width:500px; height:500px; "
                    >
                </div>
                <div class="col-md-8">
                    <div class="card-body" style="margin-left:100px; margin-top: 10px;">
                        <h6 class="card-title">Collection : {{ userdata.product_collection }}</h6>
                        <h6 class="card-title">Price : {{ userdata.product_price }}</h6>
                        <h6 class="card-title">Category : {{ userdata.product_category }}</h6>
                        <h6 class="card-title">Description : {{ userdata.product_description }}</h6>
                        <h6 class="card-title">Size : {{ userdata.product_size }}</h6>
                        <h6 class="card-title">Color : {{ userdata.product_color }}</h6>
                    </div>


                    <div style="margin-left:120px">
                        {% if cart_obj %}

                            <form method="post" action="{% url 'shop:remove_from_cart' cart_obj.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger mb-2"><span
                                        class="badge bg-white text-danger "></span>Remove From Cart

                                </button>
                            </form>

                        {% else %}

                            <form method="post" action="{% url 'shop:add_to_cart' userdata.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-info mb-2">
                                    Add To Cart <span class="badgbadgee bg-white text-info"></span>
                                </button>
                            </form>

                        {% endif %}

                        {% if wishlist_obj %}

                            <form method="post" action="{% url 'shop:remove_item' wishlist_obj.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger mb-2"><span
                                        class="badge bg-white text-danger "></span>Remove From Wishlist

                                </button>
                            </form>

                        {% else %}

                            <form method="post" action="{% url 'shop:add_to_wishlist' userdata.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-warning mb-2">
                                    Add To Wishlist <span class="badge bg-white text-warning"></span>
                                </button>
                            </form>

                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </main>
{% endblock %}

shop/templates/shop.html
{% extends 'index.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <main id="main" class="main">

        <section class="ftco-section bg-light ">
            <div class="card style="  >
                <div class="row " style="margin-left: 120px">
                    <div class="col-md-8 col-lg-10 order-md-last">
                        <div class="row">


                            {% for i in products %}
                                <div class="col-sm-6 col-md-8 col-lg-4 ftco-animate" >
                                    <div class="product card mt-4"  >

                                        <a href="{% url 'shop:product_detail' pk=i.pk %}" class="img-prod mt-4">
                                            <img class="img-fluid" src="{{ i.product_image.url }}"
                                                 alt="Colorlib Template"
                                                 style="width:180px; height:200px; margin-left:20px">

                                            <div class="overlay"></div>
                                        </a>
                                        <div class="text py-3 px-5" style="text-align: center">
                                            <div class="price badge border-dark border-1 text-dark"
                                                 style="font-size:large">
{#                                                here we use (get_       _display) to use  first capital in model of product#}
                                                <p> {{ i.get_product_collection_display }}-{{ i.product_category }}</p>
                                                <p>$ : {{ i.product_price }}</p>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}