mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('registration/', include('registration.urls', namespace='registration')),
    path('shop/', include('shop.urls', namespace='shop')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from registration import views
from django.views.generic.edit import CreateView

app_name = 'registration'
urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'
urlpatterns = [
    # path('shop/', views.Shop.as_view(), name='shop'),
    path('product_view/', views.ShowProductView.as_view(), name='product_view'),
    path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name='product_detail'),

    path('add_to_wishlist/<int:pk>/', views.AddProductToWishlist.as_view(), name='add_to_wishlist'),
    path('wishlist/', views.WishlistView.as_view(), name='wishlist'),
    path('remove_item/<int:pk>/', views.RemoveFromWishlist.as_view(), name='remove_item'),

    path('add_to_cart/<int:pk>/', views.AddProductToCart.as_view(), name="add_to_cart"),
    # path('cart/', views.CartView.as_view(), name='cart'),
    path('remove_from_cart/<int:pk>/', views.RemoveFromCart.as_view(), name='remove_from_cart'),

    path('cart_update/<int:pk>/', views.CartFormSetUpdateView.as_view(), name='cart_update'),

    path('user_info/', views.UserInfoView.as_view(), name='user_info'),
    path('order/', views.OrderView.as_view(), name='order')

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Nice-Store</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
     <!-- external Main CSS File -->
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Source+Sans+Pro" rel="stylesheet">



</head>

<body>

{% block layout %}
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
{% endblock %}
{% block css_external %}
{% endblock %}



<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->

<script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
<script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
<script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
<script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
<script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'assets/js/main.js' %}"></script>

<!-- exclude jquery for total_price -->
   <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>






</body>

{% block js %}
{% endblock %}
</html>

templates/header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <img src="{% static 'assets/img/logo.png' %}" alt="">
            <span class="d-none d-lg-block">Nice-Store</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
            <input type="text" name="query" placeholder="Search" title="Enter search keyword">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->


            {% if user.is_authenticated %}



                <li class="nav-item dropdown pe-3">

                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">

                    <span class="d-none d-md-block dropdown-toggle ps-2">Welcome : {{ user.username }}</span>
                </a>

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                <li class="dropdown-header">
                    <h6 >Name : <span class="badge border-success border-1 text-primary">{{ user.username }}</span></h6>

                 <h6> Usertype :  <span class="badge border-primary border-1 text-success">{{ user.usercreate.usertype }}</span></h6>


                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>

                <li>
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'profile' pk=user.id %}">
                        <i class="bi bi-person"></i>

                        <span>My Profile</span>
                    </a>
                </li>


                <li>
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'registration:logout' %}">
                        <i class="bi bi-box-arrow-right"></i>
                        <span>Sign Out</span>
                    </a>
                </li>


            {% else %}

                <li class="nav-item">
                    <a class="nav-link collapsed" href="{% url 'registration:register' %}">
                        <i class="bi bi-card-list"></i>
                        <span>Register</span>
                    </a>
                </li><!-- End Register Page Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" href="{% url 'registration:login' %}">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Login</span>
                    </a>
                </li>

            {% endif %}

            </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

templates/index.html
{% extends 'base.html' %}
{% block layout %}
    {% include 'header.html' %}
{% endblock %}
{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

templates/seller_index_.html
{% extends 'base.html' %}
{% block layout %}
    {% include 'header.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'sidebar.html' %}
{% endblock %}

{% block content %}
{% endblock %}

templates/sidebar.html
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
        <li class="nav-item">
            <a class="nav-link " href="{% url 'index' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->
        {% if request.user.usercreate.usertype == 'user' %}
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'shop:product_view' %}">
                    <i class="bi bi-grid-3x3-gap-fill"></i>
                    <span>Shop</span>
                </a>
            </li>
            <li class="nav-item">
                {#   cart_set <---- all data in user goes into cart_set  --->   FORMSET  CART  <---#}
                {% if request.user.usercreate.cart_set.first.id %}
                    <a class="nav-link collapsed"
                       href="{% url 'shop:cart_update' request.user.usercreate.cart_set.first.id %}">
                        <i class="bi bi-cart-plus-fill"></i>
                        <span>Cart</span>
                        <span class="badge bg-success badge-number">{{ total_items }}</span>
                    </a>
                {% else %}
                    <a class="nav-link collapsed"
                       href="#">
                        <i class="bi bi-cart-plus-fill"></i>
                        <span>Cart</span>
                        <span class="badge bg-success badge-number">0</span>
                    </a>
                {% endif %}
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'shop:wishlist' %}">
                    <i class="bi bi-heart-fill"></i>
                    <span>Wishlist</span>
                    <span class="badge bg-primary badge-number">{{ wishlist_count }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'shop:order' %}">
                    <i class="bi bi-heart-fill"></i>
                    <span>Order</span>

                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'product_rating' %}">
                    <i class="bi bi-person"></i>
                    <span>Rating</span>
                </a>
            </li>
        {% else %}

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'view_product' %}">
                    <i class="bi bi-image-alt"></i>
                    <span>View Product</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'category' %}">
                    <i class="bi bi-plus-square-fill"></i>
                    <span>SET-UP-Category</span>
                </a>
            </li>

            {#            <li class="nav-item">#}
            {#                <a class="nav-link collapsed" href="#">#}
            {#                    <i class="bi bi-plus-square-fill"></i>#}
            {#                    <span>SET-UP-Collection</span>#}
            {#                </a>#}
            {#            </li>#}
            {#            <li class="nav-item">#}
            {#                <a class="nav-link collapsed" href="#">#}
            {#                    <i class="bi bi-plus-square-fill"></i>#}
            {#                    <span>SET-UP-Size</span>#}
            {#                </a>#}
            {#            </li>#}
            {##}
            {#            <li class="nav-item">#}
            {#                <a class="nav-link collapsed" href="#">#}
            {#                    <i class="bi bi-plus-square-fill"></i>#}
            {#                    <span>SET-UP-color</span>#}
            {#                </a>#}
            {#            </li>#}

        {% endif %}
    </ul>
</aside><!-- End Sidebar-->